- readme.md
- source/lib/compiler.ts
This small fix allows you to use top-level await in your test files. We can simply ignore the error by checking the error code and filter it out of our diagnostics list.
The only downside is that VSCode still shows it as an error but running `tsd-check` works perfectly fine.
I don't think there's much we can do about that.
Is this good enough for you @sindresorhus?
> Support top-level await - fixes #1

- source/cli.ts
I ran into the `The type definition index.test-d.ts does not exist. Create one and try again.` error due to a naming mistake, but didn't realise until I made this change to print the error output. 
Happy to adjust formatting if this manner of printing the entire error isn't desired.
> fix: print error output

- source/lib/index.ts
- source/lib/rules/files-property.ts
- source/test/fixtures/test-in-subdir/package.json
- source/test/fixtures/test-in-subdir/src/index.d.ts
- source/test/fixtures/test-in-subdir/src/index.js
- source/test/fixtures/test-in-subdir/src/index.test-d.ts
- source/test/fixtures/test-non-barrel-main-via-types/foo.d.ts
- source/test/fixtures/test-non-barrel-main-via-types/foo.js
- source/test/fixtures/test-non-barrel-main-via-types/foo.test-d.ts
- source/test/fixtures/test-non-barrel-main-via-types/package.json
- source/test/fixtures/test-non-barrel-main/foo.d.ts
- source/test/fixtures/test-non-barrel-main/foo.js
- source/test/fixtures/test-non-barrel-main/foo.test-d.ts
- source/test/fixtures/test-non-barrel-main/package.json
- source/test/test.ts
This fixes following problems:
- allow types to be defined in `types` field instead of `typings`
- check for full (relative) path to types file when testing the `files` field, not only for the filename
>  Use `types` property, correctly test `files` for types in project sub-dirs

- package.json
- source/lib/compiler.ts
- source/test/fixtures/failure-strict-null-checks/index.d.ts
- source/test/fixtures/failure-strict-null-checks/index.js
- source/test/fixtures/failure-strict-null-checks/index.test-d.ts
- source/test/fixtures/failure-strict-null-checks/package.json
- source/test/fixtures/non-strict-check-with-config/index.d.ts
- source/test/fixtures/non-strict-check-with-config/index.js
- source/test/fixtures/non-strict-check-with-config/index.test-d.ts
- source/test/fixtures/non-strict-check-with-config/package.json
- source/test/test.ts
This PR changes the compiler so that it will respect the config in `package.json`s  `tsd-check.compilerOptions` field and pass this config through to the TS compiler.
> Make it strict by default and add ability to configure `compilerOptions`

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/values/index.test-d.ts
`ignoreError` should ignore more diagnostic errors:
- "property does not exist on type"
- "cannot assign to read-only property"
This PR adds the according diagnostic codes and filters them away when diagnostic is reported to be in an `expectError` statement.
> Ignore more diagnostics with `expectError`

- source/lib/compiler.ts
- source/test/fixtures/expect-error/values/index.test-d.ts
Currently, `expectError` detection only checks statements in the outermost layer of a file. This misses all `expectError` statements that are nested inside of blocks (like `if` or `try`) producing false positives during linting.
This PR extends this detection mechanism to walk through the whole syntax tree to find `expectError` statements.
> Detect `expectError` statements in nested blocks

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/values/index.d.ts
- source/test/fixtures/expect-error/values/index.test-d.ts
> Ignore required parameter count errors with `expectError`

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/test.ts
👋  It looks like TS 3.6 has a new error code which isn't classed as being ignorable in a test, this adds that. As well as providing a bit of error info when that first diagnostics. test fails. 
I'm fine with ditching the extra info on the assertion.
> Ignore no overload matches error in expectError assertion

- package.json
- source/lib/index.ts
- source/test/fixtures/lib-config/failure-missing-lib/index.d.ts
- source/test/fixtures/lib-config/failure-missing-lib/index.js
- source/test/fixtures/lib-config/failure-missing-lib/index.test-d.ts
- source/test/fixtures/lib-config/lib-as-triple-slash-reference/index.d.ts
- source/test/fixtures/lib-config/lib-as-triple-slash-reference/index.js
- source/test/fixtures/lib-config/lib-as-triple-slash-reference/index.test-d.ts
- source/test/fixtures/test-directory/tsx/index.d.ts
- source/test/fixtures/test-directory/tsx/index.js
- source/test/fixtures/test-directory/tsx/package.json
- source/test/fixtures/test-directory/tsx/test-d/unicorn.tsx
- source/test/fixtures/tsx/index.d.ts
- source/test/fixtures/tsx/index.js
- source/test/fixtures/tsx/index.test-d.tsx
- source/test/fixtures/tsx/package.json
- source/test/test.ts
This PR adds support for JSX. Not sure if I did everything correctly, so could use some reviewing here :).
// @fregante
> Add support for JSX - fixes #15

- package.json
- source/lib/rules/files-property.ts
- source/test/fixtures/files-folder/package.json
- source/test/fixtures/files-glob/package.json
- source/test/test.ts
files can contain directories and globs: https://docs.npmjs.com/files/package.json#files
This fixes it, including tests.
It also fixes a wrong url in the package.json
> Add support for globbing patterns in files property - fixes #69

- package.json
eslint-formatter-pretty@4 requires node 10, and breaks compatibility with 8:
https://github.com/sindresorhus/eslint-formatter-pretty/commit/2b21776806574f6cfb255c8ffc3479f0a72db00c#diff-168726dbe96b3ce427e7fedce31bb0bc
Noticed this in a failing test when upgrading tsd to 0.12:
```
/home/travis/build/bendrucker/snakecase-keys/node_modules/eslint-formatter-pretty/index.js:127
} catch {
^
SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> …
```
> Downgrade eslint-formatter-pretty to support Node.js 8

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/values/index.d.ts
- source/test/fixtures/expect-error/values/index.test-d.ts
> Detect "Type X has no properties in common with type Y" in `expectError` (TS2559)

- source/lib/compiler.ts
- source/lib/parser.ts
- source/test/fixtures/expect-error/functions/index.d.ts
- source/test/fixtures/expect-error/functions/index.js
- source/test/fixtures/expect-error/functions/index.test-d.ts
> Handle multiple diagnostic errors in a single `expectError` assertion

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/functions/index.d.ts
- source/test/fixtures/expect-error/functions/index.js
- source/test/fixtures/expect-error/functions/index.test-d.ts
- source/test/fixtures/expect-error/generics/index.d.ts
- source/test/fixtures/expect-error/generics/index.js
- source/test/fixtures/expect-error/generics/index.test-d.ts
This PR extends the errors swallowed by usage of `expectError` for the following 2 errors:
- function argument count mismatch for overloaded functions
- function type argument count mismatch for overloaded functions
> Allow `expectError` directives to detect parameter count mismatches

- package.json
- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/classes/index.test-d.ts
- source/test/fixtures/expect-error/classes/package.json
> Upgrade to ts@4.3, allow `expectError` to detect `override` related errors

- source/lib/assertions/index.ts
- source/lib/compiler.ts
- source/test/fixtures/exclude-node-modules/index.d.ts
- source/test/fixtures/exclude-node-modules/index.js
- source/test/fixtures/exclude-node-modules/index.test-d.ts
- source/test/fixtures/exclude-node-modules/package.json
- source/test/test.ts
I've tried a few different things here but it seems that ignoring diagnostics from `node_modules` folders is a good enough workaround.
An actual solution for this would be support from `tsc` to allow type-checking project-local `.d.ts` files while skipping `.d.ts` files from `node_modules`. The way things are right now, `skipLibCheck` will disable type-checking `.d.ts` files everywhere which we definitely don't want. On the other hand, skipping type-checking for types from `node_modules` would bring enormous performance improvements, most time is spent by checking types there.
I've also tried to mess a bit with `tsc`, mostly by monkey-patching stuff. The problem is that it's pretty much impossible to know in advance which `.d.ts` files are required to correctly type check an application …
> Ignore errors from libs in `node_modules` folders

- source/lib/rules/files-property.ts
- source/lib/rules/types-property.ts
- source/test/fixtures/utils.ts
- source/test/test.ts
- much more useful error reports when a mismatch happens
- unify how rules report paths to `package.json`, report them as relative to `context.cwd` (possibly breaking), same as all other disagnostics
> Use ava's diff comparison view to report assertion mismatches during tests

- source/test/fixtures/identicality/identical/index.test-d.ts
- source/test/fixtures/identicality/not-identical/index.test-d.ts
- source/test/identicality.ts
The problems described in #78 and #82 are not reproducible in current version of `tsd`. I've tested it with different versions of `typescript`, down to 4.0.
Closes #78
Closes #82
> Add tests for identicality checks of `any`/`never` type parameters to `expectType`/`expectNotType`

- source/lib/rules/files-property.ts
- source/test/fixtures/files-gitignore-patterns/negative-pattern-negated/index.js
- source/test/fixtures/files-gitignore-patterns/negative-pattern-negated/package.json
- source/test/fixtures/files-gitignore-patterns/negative-pattern-negated/types/index.d.ts
- source/test/fixtures/files-gitignore-patterns/negative-pattern-negated/types/index.test-d.ts
- source/test/fixtures/files-gitignore-patterns/negative-pattern/index.d.ts
- source/test/fixtures/files-gitignore-patterns/negative-pattern/index.js
- source/test/fixtures/files-gitignore-patterns/negative-pattern/index.test-d.ts
- source/test/fixtures/files-gitignore-patterns/negative-pattern/package.json
- source/test/fixtures/files-gitignore-patterns/root-marker-pattern/index.js
- source/test/fixtures/files-gitignore-patterns/root-marker-pattern/package.json
- source/test/fixtures/files-gitignore-patterns/root-marker-pattern/types/index.d.ts
- source/test/fixtures/files-gitignore-patterns/root-marker-pattern/types/index.test-d.ts
- source/test/test.ts
> Process gitignore-style patterns in `files` property of `package.json`

- package.json
Hello, thank you very much for your work. It is extremely helpful 🙂
TypeScript 4.5 was released yesterday, so here is a PR to reflect that to tsd.
Notably, [TypeScript 4.5 added a new way to replace built-in type definitions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#lib-node-modules) and tsd would be very helpful for testing custom type definitions.
Thank you 🙂
> Upgrade TypeScript to 4.5

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/values/index.d.ts
- source/test/fixtures/expect-error/values/index.test-d.ts
Support `Type '{0}' is not assignable to type '{1}'. Did you mean '{2}'?` (TS2820) error for string literal unions.
Fixes: #138
> Make `expectError` support TS2820 error introduced in TypeScript 4.5

- readme.md
- source/lib/config.ts
- source/test/fixtures/module-resolution/node16-from-package-json/index.d.ts
- source/test/fixtures/module-resolution/node16-from-package-json/index.js
- source/test/fixtures/module-resolution/node16-from-package-json/index.test-d.ts
- source/test/fixtures/module-resolution/node16-from-package-json/package.json
- source/test/fixtures/module-resolution/node16-from-tsconfig-json/index.d.ts
- source/test/fixtures/module-resolution/node16-from-tsconfig-json/index.js
- source/test/fixtures/module-resolution/node16-from-tsconfig-json/index.test-d.ts
- source/test/fixtures/module-resolution/node16-from-tsconfig-json/package.json
- source/test/fixtures/module-resolution/node16-from-tsconfig-json/tsconfig.json
- source/test/fixtures/module-resolution/nodenext-from-package-json/index.d.ts
- source/test/fixtures/module-resolution/nodenext-from-package-json/index.js
- source/test/fixtures/module-resolution/nodenext-from-package-json/index.test-d.ts
- source/test/fixtures/module-resolution/nodenext-from-package-json/package.json
- source/test/fixtures/module-resolution/nodenext-from-tsconfig-json/index.d.ts
- source/test/fixtures/module-resolution/nodenext-from-tsconfig-json/index.js
- source/test/fixtures/module-resolution/nodenext-from-tsconfig-json/index.test-d.ts
- source/test/fixtures/module-resolution/nodenext-from-tsconfig-json/package.json
- source/test/fixtures/module-resolution/nodenext-from-tsconfig-json/tsconfig.json
- source/test/test.ts
Edit: Sorry, failed to leave a description!
This change aims to set the `moduleResolution` to `nodenext` or `node16` when appropriate.
This allows for using `nodenext` features inside `tsd` test files, such as `self-module imports`, which I have tested here.
This is the feature that I am missing to incorporate `tsd` in https://github.com/dotcore64/p-from-callback/pull/15
Thanks!
> Add support for nodenext moduleResolution

- readme.md
- source/lib/assertions/assert.ts
- source/lib/assertions/handlers/assignability.ts
- source/lib/assertions/handlers/expect-deprecated.ts
- source/lib/assertions/handlers/identicality.ts
- source/lib/assertions/handlers/informational.ts
In https://github.com/SamVerschueren/tsd/pull/130#discussion_r967803264, it's pointed out that the descriptions of each assertion is different between the readme and the `assert.ts` file. For example, `expectDeprecated()` is defined as:
https://github.com/SamVerschueren/tsd/blob/14f28125e74ca533645d264209e7f9fd0e778568/source/lib/assertions/assert.ts#L55-L63
Whereas the readme says:
> ### expectDeprecated(value)
> 
> Check that `value` is marked a [`@deprecated`](https://jsdoc.app/tags-deprecated.html).
> 
---
This PR changes each assertion description to consistently use `expression` and to say:
> Asserts that (the type of) `expression` . . .
In addition, the documentation comment of each assertion handler follows the same form:
```ts
/**
* Asserts that the argument of the assertion ... …
```
> Unify Documentation for Assertions

- readme.md
At some point along the way of merging in #156, the `--typings` heading got lost:
https://github.com/SamVerschueren/tsd/blob/b777588a19b01e8a0e861c32164231d9f06e278d/readme.md?plain=1#L242-L256
This PR adds it back.
> README fix - `--typings`

- package.json
Using a glob with ESLint requires [double quotes on Windows](https://eslint.org/docs/latest/user-guide/command-line-interface).
> ESLint Windows Fix

- source/lib/parser.ts
> fix(parser): handle empty maybeAlias

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/generics/index.d.ts
- source/test/fixtures/expect-error/generics/index.test-d.ts
Adds a `DiagnosticCode` to check for TS error `2707`, [`"Generic type '${0}' requires between ${1} and ${2} type arguments."`](https://github.com/microsoft/TypeScript/blob/43cc362cef72e5fa1372f59736a9c4b55d85def0/src/compiler/diagnosticMessages.json#L3094-L3097). Came up while trying to add a test for type-fest.
> fix(`DiagnosticCode`): add `ts(2707)`

- source/cli.ts
- source/test/cli.ts
Continued from #152. Closes #137.
Implements requested changes from stale PR and adds a test case.
Closes #152
> feat(`cli`): log stacktrace on failure

- readme.md
- source/index.ts
- source/test/cli.ts
Closes #147.
With #165 changing the formatter, it makes more sense to provide our formatter so that programmatic users can prettify their output, too.
`tsd` is still the default export, but the formatter can be imported like so:
```ts
import tsd, {formatter} from 'tsd';
```
> Export formatter

- source/index.ts
Changes formatter export from
```ts
import formatter from './lib/formatter';
export {formatter};
```
to
```ts
export {default as formatter} from './lib/formatter';
```
> fix(`formatter`): make export simpler

- package.json
- source/cli.ts
- source/test/cli.ts
- source/test/diff.ts
- source/test/fixtures/utils.ts
Starting in `v0.26.1`, successful runs of the CLI (i.e. when it doesn't crash) incorrectly report an error and error stack while running `tsd`:
```
Error running tsd: Error: 
index.test-d.ts:26:0
✖  25:0  Expected an error, but found none.  
✖  26:0  ) expected.                         
2 errors
at ~/node_modules/tsd/dist/cli.js:64:19
at Generator.next (<anonymous>)
at fulfilled (~/node_modules/tsd/dist/cli.js:6:58)
```
This PR restores the old behavior and makes sure that the error message and stack are only displayed when `tsd` crashes.
> fix: don't log stacktrace if cli succeeds (regression)

- readme.md
- source/lib/config.ts
Sets `tsconfig` option `noUnusedLocals: false` by default. Based on https://github.com/sindresorhus/type-fest/pull/560#discussion_r1133009963
Also documents further defaults in the readme.
> Make `tsd` ignore unused locals by default

- source/cli.ts
- source/lib/index.ts
- source/lib/interfaces.ts
- source/test/cli.ts
- source/test/test.ts
Similar to #182, `tsd` will also display an error stack on failure (even if it didn't crash), e.g. when no `index.d.ts` is found:
```
Error running tsd:
Error: The type definition \`index.d.ts\` does not exist at \`.../fixtures/no-tsd/index.d.ts\`. Is the path correct? Create one and try again.
at .../lib/index.js:31:15
at Generator.next (<anonymous>)
at fulfilled (.../lib/index.js:5:58)
```
This should only show the error message:
```
The type definition \`index.d.ts\` does not exist at \`.../fixtures/no-tsd/index.d.ts\`. Is the path correct? Create one and try again.
```
This PR adds a custom `TsdError` to differentiate between the two cases:
```ts
try {
// ... run tsd
} catch (error: unknown) {
const potentialError = error as Error | undefined;
if (potentialError instanceof TsdError) { …
```
> Fix error messages when `tsd` fails

- source/lib/compiler.ts
- source/lib/interfaces.ts
Followup to #202 and #204. After upgrading in https://github.com/Automattic/mongoose/pull/14221 to tsd@0.30, I started getting the following errors:
```
test/types/base.test.ts:61:29
✖   61:2   Found an error that tsd does not currently support (ts2353), consider creating an issue on GitHub.                                                                                                                                                                                                                                                               
✖   61:29  Object literal may only specify known properties, and invalid does not exist in type { allowDiskUse?: boolean | undefined; applyPluginsToChildSchemas?: boolean | undefined; applyPluginsToDiscriminators?: boolean | undefined; autoCreate?: …
```
> Add code 2561 to known errors

- source/lib/compiler.ts
- source/lib/interfaces.ts
Immutable-js is moving towards using `tsd` on the next release and I encountered this error in one test case being migrated. 
https://github.com/arnfaldur/immutable-js/blob/a23550e48343b8ae902688856fd8b9f6ae1b15ec/type-definitions/ts-tests/map.ts#L275
> Add code 2740 to known errors

- source/lib/compiler.ts
- source/lib/interfaces.ts
- source/test/fixtures/expect-error/values/index.test-d.ts
- source/test/fixtures/expect-error/values/package.json
https://typescript.tv/errors/#ts18046
> Add `ts18046` to known errors

- source/lib/compiler.ts
- source/lib/interfaces.ts
Fixes #215.
Please note that error code TS2740 was added in #208, but despite having a different error code, the error messages for TS2739 and TS2740 are otherwise identical. So I've also renamed the enum members to include "variant 1" and "variant 2".
> Add `ts2739` to known errors
